installation directory saving

diff --git a/bfmake b/bfmake
--- a/bfmake
+++ b/bfmake
@@ -1,11 +1,14 @@
 #!/bin/bash -e
 
+if [ ! -f "~/.asmbf" ]; then
+	echo "Error: asm2bf not installed properly."
+	exit 1
+fi
+
+bench=$(cat ~/.asmbf)
+
 if [ "$1" == "-no-strip" ]; then
-	name=$(echo "$2" | cut -f 1 -d '.')
-
-	{ cat /bin/asmbf/lib/lib-bfm.lua ; cat "$2" | sed -e "1!b" -e '/#/d' ; } | /bin/asmbf/bfpp | /bin/asmbf/bflabels | /bin/asmbf/bfdata | sed '/^#/ d' | /bin/asmbf/bfasm > "${2%.*}.b"
+	{ cat "${!bench}lib/lib-bfm.lua" ; cat "$2" | sed -e "1!b" -e '/#/d' ; } | "${!bench}bfpp" | "${!bench}bflabels" | "${!bench}bfdata" | sed '/^#/ d' | "${!bench}bfasm" > "${2%.*}.b"
 else
-	name=$(echo "$1" | cut -f 1 -d '.')
-
-	{ cat /bin/asmbf/lib/lib-bfm.lua ; cat "$1" | sed -e "1!b" -e '/#/d' ; } | /bin/asmbf/bfpp | /bin/asmbf/bflabels | /bin/asmbf/bfdata | sed '/^#/ d' | /bin/asmbf/bfasm | /bin/asmbf/bfstrip > "${1%.*}.b"
+	{ cat "${!bench}lib/lib-bfm.lua" ; cat "$1" | sed -e "1!b" -e '/#/d' ; } | "${!bench}bfpp" | "${!bench}bflabels" | "${!bench}bfdata" | sed '/^#/ d' | "${!bench}bfasm" | "${!bench}bfstrip" > "${1%.*}.b"
 fi
